sudo: false
dist: trusty
language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - env: PRO_VERSION='11'
      install:
        - java pro_wrapper.java version

    - env: PRO_VERSION='11 Graal'
      install:
        - java pro_wrapper.java version
        - sed -i s/JLINK_VM_OPTIONS=/JLINK_VM_OPTIONS="\"-XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler\""/g ./pro/bin/pro
        - cat ./pro/bin/pro

script:
  - ./pro/bin/pro version
  - java pro_wrapper.java build perfer

