sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - env: PRO_VERSION='10'
      install:
        - wget --no-check-certificate https://github.com/forax/pro/releases/download/0.10-17/pro-linux.zip
        - unzip pro-linux.zip

    - env: PRO_VERSION='10 Graal'
      install:
        - wget --no-check-certificate https://github.com/forax/pro/releases/download/0.10-17/pro-linux.zip
        - unzip pro-linux.zip
        - cp .travis/pro-graal pro/bin/pro

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro build perfer

