sudo: false
dist: trusty
language: java

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

matrix:
  include:
    - env: PRO_VERSION='9'
      install:
        - wget --no-check-certificate https://github.com/forax/pro/releases/download/v0.9.181b/pro-9-b181b-linux.tar.gz
        - tar -xzf pro-9-b181b-linux.tar.gz

    - env: PRO_VERSION='10'
      install:
        - wget --no-check-certificate https://github.com/forax/pro/releases/download/v0.10%2B44a/pro-10.44a-linux.tar.gz
        - tar -xzf pro-10.44a-linux.tar.gz

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro

